#!/bin/bash
source "$(dirname "$0")/log_info.sh"
# Usage: gac "commit message"

if [ -z "$1" ]; then
  echo "Error: Commit message required. Usage: gac \"commit message\""
  exit 1
fi

log_run git add .
log_run git commit -m "$1"
