#!/bin/bash
source "$(dirname "$0")/log_info.sh"
# gls.sh - git log with commit time, oneline, -n <number>

if [ -z "$1" ]; then
  echo "Error: Number of logs required."
  exit 1
fi

log_run git log --pretty=format:"%h %ad %s" --date=iso -n "$1"