#!/bin/bash
echo "mvn versions:display-plugin-updates | grep -E 'RELEASE|Final|GA|\.\d+$' | grep -v -i 'alpha\|beta\|rc\|prerelease'"
mvn versions:display-plugin-updates | grep -E 'RELEASE|Final|GA|\.\d+$' | grep -v -i 'alpha\|beta\|rc\|prerelease'
